# Generated by Django 5.2.1 on 2025-05-30 06:36

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listpostmodel',
            name='image',
            field=models.ImageField(default=apps.blog.models.get_default_product_image, upload_to='images/%Y/%m/%d'),
        ),
    ]
