# Generated by Django 5.2.1 on 2025-05-30 15:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_listpostmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listpostmodel',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
