# Generated by Django 5.2.1 on 2025-05-30 15:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_listpostmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listpostmodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
